# -*- coding: utf-8 -*-
"""5.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWmMh5Br53qIZ_9emn0evJFIMv6o_Y3Q
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Параметры волны
length = 100  # Длина пространства
num_points = 500  # Количество точек для отображения
amplitude = 1  # Амплитуда волны
frequency = 0.1  # Частота волны
speed = 0.1  # Скорость распространения волны

# Создаем массив координат
x = np.linspace(0, length, num_points)

# Функция для вычисления амплитуды волны в зависимости от времени
def wave_function(x, t):
    return amplitude * np.sin(2 * np.pi * frequency * (x - speed * t))

# Создаем фигуру и оси для анимации
fig, ax = plt.subplots()
line, = ax.plot(x, wave_function(x, 0), label='Волна')

# Настраиваем оси и заголовок
ax.set_xlabel('Координата X')
ax.set_ylabel('Амплитуда')
ax.set_title('Распространение волны')
ax.legend()

# Функция для обновления анимации
def update(frame):
    t = frame / 10.0  # Время в секундах
    y = wave_function(x, t)
    line.set_ydata(y)
    return line,

# Создаем анимацию
ani = animation.FuncAnimation(fig, update, frames=range(500), blit=True)

# Отображаем анимацию
plt.show()