# -*- coding: utf-8 -*-
"""5.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWmMh5Br53qIZ_9emn0evJFIMv6o_Y3Q
"""

import random

array = [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

def place_ship(arr):
    while True:
        orientation = random.choice(['horizontal', 'vertical'])
        if orientation == 'horizontal':
            x = random.randint(0, 4)
            y = random.randint(0, 3)
            if arr[x][y] == 0 and arr[x][y + 1] == 0:
                arr[x][y] = 1
                arr[x][y + 1] = 1
                break
        else:
            x = random.randint(0, 3)
            y = random.randint(0, 4)
            if arr[x][y] == 0 and arr[x + 1][y] == 0:
                arr[x][y] = 1
                arr[x + 1][y] = 1
                break

# Размещаем корабль на поле
place_ship(array)

def game(arr):
    hits = 0
    total_hits = 2  # Количество клеток корабля
    while hits != total_hits:
        print('Введите координаты (через пробел)')
        coords = input().split()
        x = int(coords[1]) - 1
        y = int(coords[0]) - 1
        if arr[x][y] == 1:
            arr[x][y] = '+'
            hits += 1
            print('Попадение!')
        else:
            arr[x][y] = '-'
            print('Промах!')
        for row in arr:
            print(row)
    print('ПОБЕДА!!!')
    return 0

game(array)